# Generated by Django 3.2 on 2021-04-12 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=80)),
                ('parola', models.CharField(max_length=50)),
                ('tel_numara', models.CharField(max_length=10)),
                ('kayit_tarihi', models.DateTimeField(auto_now_add=True)),
                ('aktif', models.BooleanField(default=True)),
            ],
        ),
    ]
