# Generated by Django 3.2 on 2021-04-12 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='parola',
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.EmailField(default='', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='kayit_tarihi',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
